/**
 * The ten prop pieces, hand-drawn: a one-character palette and 16 rows of 16 characters (`.` is transparent). They stand in
 * the lower part of the tile with a dark outline; each theme has two (see THEMES in src/art/theme.ts).
 */
export const PROP_IMAGES = {
  prop_supply_crate: {
    palette: { k: '#0b0c12', a: '#6b7a4a', A: '#4f5c36', b: '#8c9a64', m: '#8a8a99' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '..kkkkkkkkkkkk..',
      '..kbbbbbbbbbbk..',
      '..kbbbbbbbbbbk..',
      '..kmmmmmmmmmmk..',
      '..kaaaaaaaaaak..',
      '..kaaaaaaaaaak..',
      '..kmmmmmmmmmmk..',
      '..kAAAAAAAAAAk..',
      '..kAAAAAAAAAAk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
    ],
  },
  prop_oil_drum: {
    palette: { k: '#0b0c12', a: '#5a6b7d', A: '#3f4d5c', b: '#7d8fa3', r: '#b5651d' },
    rows: [
      '................',
      '................',
      '.....kkkkkk.....',
      '....kbbbbbbk....',
      '....kaaaaaak....',
      '....krrrrrrk....',
      '....kaaaaaak....',
      '....kaaaaaak....',
      '....krrrrrrk....',
      '....kaaaaaak....',
      '....kAAAAAAk....',
      '....kAAAAAAk....',
      '.....kkkkkk.....',
      '................',
      '................',
      '................',
    ],
  },
  prop_wood_crate: {
    palette: { k: '#0b0c12', a: '#b5803a', A: '#7a5222', b: '#d9a65a' },
    rows: [
      '................',
      '................',
      '................',
      '..kkkkkkkkkkkk..',
      '..kbbbbbbbbbbk..',
      '..kaAaaaaaaAak..',
      '..kaaAaaaaAaak..',
      '..kaaaAaaAaaak..',
      '..kaaaaAAaaaak..',
      '..kaaaAaaAaaak..',
      '..kaaAaaaaAaak..',
      '..kaAaaaaaaAak..',
      '..kAAAAAAAAAAk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
    ],
  },
  prop_barrel: {
    palette: { k: '#0b0c12', a: '#a8702e', A: '#6b4420', b: '#cf9548', m: '#4a4a55' },
    rows: [
      '................',
      '................',
      '.....kkkkkk.....',
      '...kkbbbbbbkk...',
      '...kbaaaaaabk...',
      '...kmmmmmmmmk...',
      '...kaaaaaaaak...',
      '...kaaaaaaaak...',
      '...kmmmmmmmmk...',
      '...kaaaaaaaak...',
      '...kAAAAAAAAk...',
      '...kkAAAAAAkk...',
      '.....kkkkkk.....',
      '................',
      '................',
      '................',
    ],
  },
  prop_machine: {
    palette: { k: '#0b0c12', a: '#5d6b7a', A: '#3f4a57', b: '#8da0b4', y: '#ffe14d', g: '#3cb371', r: '#e04040' },
    rows: [
      '................',
      '................',
      '..kkkkkkkkkkkk..',
      '..kbbbbbbbbbbk..',
      '..kbaaaaaaaabk..',
      '..kbakkkkkkabk..',
      '..kbakggggkabk..',
      '..kbakkkkkkabk..',
      '..kbaaaaaaaabk..',
      '..kbayaraaaabk..',
      '..kbaaaaaaaabk..',
      '..kAAAAAAAAAAk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
      '................',
    ],
  },
  prop_tank: {
    palette: { k: '#0b0c12', a: '#6a7f94', A: '#46566a', b: '#aebdcb', o: '#e08a30' },
    rows: [
      '................',
      '................',
      '.......oo.......',
      '.......kk.......',
      '...kkkkkkkkkk...',
      '..kbbbbbbbbbbk..',
      '.kbaaaaaaaaaabk.',
      '.kaaaAaaaaAaaak.',
      '.kaaaAaaaaAaaak.',
      '.kaaaAaaaaAaaak.',
      '.kAaaAaaaaAaaAk.',
      '..kAAAAAAAAAAk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
      '................',
    ],
  },
  prop_boulder: {
    palette: { k: '#0b0c12', a: '#6e7a6a', A: '#4a5448', b: '#98a692' },
    rows: [
      '................',
      '................',
      '................',
      '.....kkkkk......',
      '...kkbbbbbkk....',
      '..kbbbaaaabbk...',
      '.kbbaaaaaaaabk..',
      '.kbaaaaAaaaaak..',
      '.kaaaaaaaaAaak..',
      '.kaaAaaaaaaaAk..',
      '.kAaaaaaaaaAAk..',
      '..kAAAAAAAAAk...',
      '...kkkkkkkkk....',
      '................',
      '................',
      '................',
    ],
  },
  prop_rocks: {
    palette: { k: '#0b0c12', a: '#6e7a6a', A: '#4a5448', b: '#98a692' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '..........kkk...',
      '....kkk..kbbak..',
      '...kbbak.kaaAk..',
      '..kbaaAkkkaAAk..',
      '..kaaAAkbbkAAk..',
      '.kkAAAkbaakkk...',
      '.kbakkkaaAAk....',
      '.kaaAAkAAAAk....',
      '..kkkkkkkkk.....',
      '................',
      '................',
      '................',
    ],
  },
  prop_pillar: {
    palette: { k: '#0b0c12', a: '#9a9ea6', A: '#6a6e76', b: '#d4d6da' },
    rows: [
      '................',
      '...kkkkkkkkkk...',
      '..kbbbbbbbbbbk..',
      '..kAAAAAAAAAAk..',
      '....kbaaaaAk....',
      '....kbaaaaAk....',
      '....kbaaaaAk....',
      '....kbaaaaAk....',
      '....kbaaaaAk....',
      '....kbaaaaAk....',
      '..kbbbbbbbbbbk..',
      '..kAAAAAAAAAAk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
      '................',
    ],
  },
  prop_urn: {
    palette: { k: '#0b0c12', a: '#a8844a', A: '#6e5430', b: '#d9bd7e', d: '#3a2a18' },
    rows: [
      '................',
      '................',
      '.....kkkkkk.....',
      '.....kbbbbk.....',
      '......kddk......',
      '.....kbaabk.....',
      '....kbaaaabk....',
      '...kbaaaaaabk...',
      '...kaaaaaaaak...',
      '...kaaaaaaaAk...',
      '....kaaaaaAk....',
      '....kAAAAAAk....',
      '.....kkkkkk.....',
      '................',
      '................',
      '................',
    ],
  },
};
